version: '3'

services: 
  vacante_db:
    container_name: vacante_db
    build: 
      context: ./db    
      dockerfile: .dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks: 
      - vacante_network
    ports: 
      - 5432:5432
    volumes: 
      - vacante_db_volume:/var/lib/postgresql/data
  vacante_be:
    depends_on: 
      - vacante_db
    container_name: vacante_be
    build: 
      context: ../vacante-backend/vacation-destinations
      dockerfile: .dockerfile
    volumes: 
      - ../vacante-backend/vacation-destinations:/vacante-be
    working_dir: /vacante-be
    environment: 
      - DATABASE_HOST=vacante_db
      - DATABASE_PORT=5432
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - urlForCrossOrigin=${urlForCrossOrigin}
    networks: 
      - vacante_network
    ports: 
      - 8080:8080 
    entrypoint: "bash -c 'java -jar ./web/target/vacation-destinations.jar'"
  vacante-fe:
    depends_on: 
      - vacante_be
    container_name: vacante-fe
    build: 
      context: ../vacation-frontend/vacation-destinations/
      dockerfile: .dockerfile
    volumes: 
      - ../vacation-frontend/vacation-destinations:/vacante-fe
    working_dir: /vacante-fe
    ports: 
      - 4200:4200
    networks: 
      - vacante_network
    entrypoint: "ng serve --host 0.0.0.0"
    


networks: 
  vacante_network:
volumes: 
  vacante_db_volume: