version: '3'

services: 
  vacante_db:
    container_name: vacante_db
    build: 
      context: ./db      
      dockerfile: .dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks: 
      - vacante_network
    ports: 
      - 5432:5432
    volumes: 
      - vacante_db_volume:/var/lib/postgresql/data

networks: 
  vacante_network:
volumes: 
  vacante_db_volume: